### ISSUE TITLE
Add App flows in the CLI

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/cli#112]
To support non-javascript NVM App integration via command line, we want to support the basic flows of the flow via the CLI. This change will require to implement a new `app` module in the `ncli` application where users can do the basic flow of the app via CLI.
```[tasklist]
### Tasks
- [x] Integrate the NVM App api in the CLI
- [x] Create a new `app` sub
- [x] Create a time subscription
- [x] Create a credits subscription
- [x] Show information of a plan
- [x] See if a user is a subscriber of a plan
- [x] Register a new agent
- [x] Register a new file
- [x] Make a Purhcase
- [x] Get an agent access token
- [ ] Query a service
- [x] Download a file
```
