### ISSUE TITLE
Manage the NVM API Key from the CLI

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/cli#119]
As a CLI user I want to be able the manage my NVM API Keys from the CLI.

```[tasklist]
### Tasks
- [x] Create a new NVM API Key
- [x] List my NVM API Keys
- [x] Revoke one of my NVM API Keys
```
