### ISSUE TITLE
CLI `v0.6` improvements

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/cli#64]
The tasks planned for the CLI `v0.6` are:

- [x] #65
- [x] #69 
- [x] The NFT SEAs must use by default transferNFT param [SDK-JS]
- [x] Use the denominator in token balances
- [x] If account address or index is given on balance we get info of just that account
- [x] In NFT show we need to retrieve some more NFT information (license doesn't work)
- [x] Get DID Royalties information
- [x] Added on-chain and metadata info in `resolve` command
- [x] Improve the search of assets
- [x] Update documentation
- [x] Add deployment of subscriptions
- [x] Re-enable `DTP`
